baseurl = "https://www.doudmine.com"
metaDataFormat = "yaml"
title = "Doudmine"
theme = "blist"

googleAnalytics = ""

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hey ðŸ‘‹ I'm Driss OUDMINE"
      introSubtitle = "Front-end & Shopify theme developer"
      introParagraph = "Develop functional user interfaces and provide a valuable experience to Shopify store owners."
      introPhoto = "/picture.jpg"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
        
    [[languages.en.menu.main]]
        name = "Contact"
        url = "contact"
        weight = 2

[params]
  description = "Doudmine - Develop functional user interfaces and provide a valuable experience to Shopify store owners"
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright Â© 2022 - Doudmine Â· All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  subtitle = "Where I share tips & tricks about Shopify in general"
  
  instagram = "https://www.instagram.com/doudmine/"
  youtube = "https://www.youtube.com/channel/UCYF73P2A2NdVr6c9aONH22w"
  pinterest = "https://www.pinterest.com/doudmine"

[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Contact"
  url = "/contact"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight
[markup]
  [markup.highlight]
    codeFences = true
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true